// <auto-generated />
using System;
using CareerAdvisor.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CareerAdvisor.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260917224920_EnableRowLevelSecurity")]
    partial class EnableRowLevelSecurity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CareerAdvisor.Api.Models.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("FacultyName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("faculty_name");

                    b.Property<int>("MinimumAps")
                        .HasColumnType("integer")
                        .HasColumnName("minimum_aps");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("OfoCode")
                        .HasColumnType("text")
                        .HasColumnName("ofo_code");

                    b.Property<string>("SaqaQualificationId")
                        .HasColumnType("text")
                        .HasColumnName("saqa_qualification_id");

                    b.Property<Guid>("UniversityId")
                        .HasColumnType("uuid")
                        .HasColumnName("university_id");

                    b.HasKey("Id")
                        .HasName("pk_courses");

                    b.HasIndex("MinimumAps")
                        .HasDatabaseName("ix_courses_minimum_aps");

                    b.HasIndex("OfoCode")
                        .HasDatabaseName("ix_courses_ofo_code");

                    b.HasIndex("SaqaQualificationId")
                        .HasDatabaseName("ix_courses_saqa_qualification_id");

                    b.HasIndex("UniversityId", "Name")
                        .IsUnique()
                        .HasDatabaseName("courses_university_name_key");

                    b.ToTable("courses", (string)null);
                });

            modelBuilder.Entity("CareerAdvisor.Api.Models.CourseSubjectRequirement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AlternativeGroupKey")
                        .HasColumnType("text")
                        .HasColumnName("alternative_group_key");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid")
                        .HasColumnName("course_id");

                    b.Property<bool>("IsCompulsory")
                        .HasColumnType("boolean")
                        .HasColumnName("is_compulsory");

                    b.Property<int>("MinimumPercentage")
                        .HasColumnType("integer")
                        .HasColumnName("minimum_percentage");

                    b.Property<string>("SubjectName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subject_name");

                    b.HasKey("Id")
                        .HasName("pk_course_subject_requirements");

                    b.HasIndex("CourseId")
                        .HasDatabaseName("ix_csr_course_id");

                    b.HasIndex("CourseId", "AlternativeGroupKey")
                        .HasDatabaseName("ix_csr_group");

                    b.ToTable("course_subject_requirements", (string)null);
                });

            modelBuilder.Entity("CareerAdvisor.Api.Models.DataSyncLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<int>("RecordsProcessed")
                        .HasColumnType("integer")
                        .HasColumnName("records_processed");

                    b.Property<DateTime>("RunAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("run_at");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_name");

                    b.Property<bool>("Success")
                        .HasColumnType("boolean")
                        .HasColumnName("success");

                    b.HasKey("Id")
                        .HasName("pk_data_sync_logs");

                    b.HasIndex("SourceName", "RunAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_data_sync_logs_source_run");

                    b.ToTable("data_sync_logs", (string)null);
                });

            modelBuilder.Entity("CareerAdvisor.Api.Models.Matriculant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<int>("MatricYear")
                        .HasColumnType("integer")
                        .HasColumnName("matric_year");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("province");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_matriculants");

                    b.HasIndex("Province")
                        .HasDatabaseName("ix_matriculants_province");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("matriculants_user_id_key");

                    b.ToTable("matriculants", (string)null);
                });

            modelBuilder.Entity("CareerAdvisor.Api.Models.MatriculantSubject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsHomeLanguage")
                        .HasColumnType("boolean")
                        .HasColumnName("is_home_language");

                    b.Property<Guid>("MatriculantId")
                        .HasColumnType("uuid")
                        .HasColumnName("matriculant_id");

                    b.Property<int>("Percentage")
                        .HasColumnType("integer")
                        .HasColumnName("percentage");

                    b.Property<string>("SubjectName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subject_name");

                    b.HasKey("Id")
                        .HasName("pk_matriculant_subjects");

                    b.HasIndex("MatriculantId")
                        .HasDatabaseName("ix_matriculant_subjects_matriculant");

                    b.HasIndex("MatriculantId", "SubjectName")
                        .IsUnique()
                        .HasDatabaseName("matriculant_subjects_unique");

                    b.ToTable("matriculant_subjects", (string)null);
                });

            modelBuilder.Entity("CareerAdvisor.Api.Models.OfoCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_synced_at");

                    b.Property<string>("MajorGroup")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("major_group");

                    b.Property<string>("SubMinorGroup")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sub_minor_group");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_ofo_codes");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ofo_codes_code_key");

                    b.HasIndex("MajorGroup")
                        .HasDatabaseName("ix_ofo_codes_major_group");

                    b.ToTable("ofo_codes", (string)null);
                });

            modelBuilder.Entity("CareerAdvisor.Api.Models.SaqaQualification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AwardingBody")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("awarding_body");

                    b.Property<int>("Credits")
                        .HasColumnType("integer")
                        .HasColumnName("credits");

                    b.Property<DateTime>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_synced_at");

                    b.Property<int>("NqfLevel")
                        .HasColumnType("integer")
                        .HasColumnName("nqf_level");

                    b.Property<string>("QualificationType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("qualification_type");

                    b.Property<string>("SaqaId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("saqa_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_saqa_qualifications");

                    b.HasIndex("NqfLevel")
                        .HasDatabaseName("ix_saqa_qualifications_nqf_level");

                    b.HasIndex("SaqaId")
                        .IsUnique()
                        .HasDatabaseName("saqa_qualifications_saqa_id_key");

                    b.ToTable("saqa_qualifications", (string)null);
                });

            modelBuilder.Entity("CareerAdvisor.Api.Models.University", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("province");

                    b.Property<string>("ShortCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("short_code");

                    b.Property<string>("Website")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("website");

                    b.HasKey("Id")
                        .HasName("pk_universities");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("universities_name_key");

                    b.HasIndex("Province")
                        .HasDatabaseName("ix_universities_province");

                    b.HasIndex("ShortCode")
                        .IsUnique()
                        .HasDatabaseName("universities_short_code_key");

                    b.ToTable("universities", (string)null);
                });

            modelBuilder.Entity("CareerAdvisor.Api.Models.Course", b =>
                {
                    b.HasOne("CareerAdvisor.Api.Models.University", "University")
                        .WithMany("Courses")
                        .HasForeignKey("UniversityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_courses_universities_university_id");

                    b.Navigation("University");
                });

            modelBuilder.Entity("CareerAdvisor.Api.Models.CourseSubjectRequirement", b =>
                {
                    b.HasOne("CareerAdvisor.Api.Models.Course", "Course")
                        .WithMany("SubjectRequirements")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_course_subject_requirements_courses_course_id");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("CareerAdvisor.Api.Models.MatriculantSubject", b =>
                {
                    b.HasOne("CareerAdvisor.Api.Models.Matriculant", "Matriculant")
                        .WithMany("Subjects")
                        .HasForeignKey("MatriculantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_matriculant_subjects_matriculants_matriculant_id");

                    b.Navigation("Matriculant");
                });

            modelBuilder.Entity("CareerAdvisor.Api.Models.Course", b =>
                {
                    b.Navigation("SubjectRequirements");
                });

            modelBuilder.Entity("CareerAdvisor.Api.Models.Matriculant", b =>
                {
                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("CareerAdvisor.Api.Models.University", b =>
                {
                    b.Navigation("Courses");
                });
#pragma warning restore 612, 618
        }
    }
}
