// <auto-generated />
using System;
using CareerAdvisor.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CareerAdvisor.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260918192120_AddMatriculantDateOfBirth")]
    partial class AddMatriculantDateOfBirth
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CareerAdvisor.Api.Models.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Details")
                        .HasColumnType("text")
                        .HasColumnName("details");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("entity_type");

                    b.HasKey("Id")
                        .HasName("pk_audit_logs");

                    b.HasIndex("EntityType", "EntityId")
                        .HasDatabaseName("ix_audit_logs_entity");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("CareerAdvisor.Api.Models.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("FacultyName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("faculty_name");

                    b.Property<int>("MinimumAps")
                        .HasColumnType("integer")
                        .HasColumnName("minimum_aps");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("OfoCode")
                        .HasColumnType("text")
                        .HasColumnName("ofo_code");

                    b.Property<string>("SaqaQualificationId")
                        .HasColumnType("text")
                        .HasColumnName("saqa_qualification_id");

                    b.Property<Guid>("UniversityId")
                        .HasColumnType("uuid")
                        .HasColumnName("university_id");

                    b.HasKey("Id")
                        .HasName("pk_courses");

                    b.HasIndex("MinimumAps")
                        .HasDatabaseName("ix_courses_minimum_aps");

                    b.HasIndex("OfoCode")
                        .HasDatabaseName("ix_courses_ofo_code");

                    b.HasIndex("SaqaQualificationId")
                        .HasDatabaseName("ix_courses_saqa_qualification_id");

                    b.HasIndex("UniversityId", "Name")
                        .IsUnique()
                        .HasDatabaseName("courses_university_name_key");

                    b.ToTable("courses", (string)null);
                });

            modelBuilder.Entity("CareerAdvisor.Api.Models.CourseSubjectRequirement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AlternativeGroupKey")
                        .HasColumnType("text")
                        .HasColumnName("alternative_group_key");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid")
                        .HasColumnName("course_id");

                    b.Property<bool>("IsCompulsory")
                        .HasColumnType("boolean")
                        .HasColumnName("is_compulsory");

                    b.Property<int>("MinimumPercentage")
                        .HasColumnType("integer")
                        .HasColumnName("minimum_percentage");

                    b.Property<string>("SubjectName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subject_name");

                    b.HasKey("Id")
                        .HasName("pk_course_subject_requirements");

                    b.HasIndex("CourseId")
                        .HasDatabaseName("ix_csr_course_id");

                    b.HasIndex("CourseId", "AlternativeGroupKey")
                        .HasDatabaseName("ix_csr_group");

                    b.ToTable("course_subject_requirements", (string)null);
                });

            modelBuilder.Entity("CareerAdvisor.Api.Models.DataSyncLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<int>("RecordsProcessed")
                        .HasColumnType("integer")
                        .HasColumnName("records_processed");

                    b.Property<DateTime>("RunAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("run_at");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_name");

                    b.Property<bool>("Success")
                        .HasColumnType("boolean")
                        .HasColumnName("success");

                    b.HasKey("Id")
                        .HasName("pk_data_sync_logs");

                    b.HasIndex("SourceName", "RunAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_data_sync_logs_source_run");

                    b.ToTable("data_sync_logs", (string)null);
                });

            modelBuilder.Entity("CareerAdvisor.Api.Models.HelpRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttachedAps")
                        .HasColumnType("integer")
                        .HasColumnName("attached_aps");

                    b.Property<string>("AttachedMarksSummary")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("attached_marks_summary");

                    b.Property<string>("Goal")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("goal");

                    b.Property<Guid>("MatriculantId")
                        .HasColumnType("uuid")
                        .HasColumnName("matriculant_id");

                    b.Property<Guid>("MentorId")
                        .HasColumnType("uuid")
                        .HasColumnName("mentor_id");

                    b.Property<string>("Need")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("need");

                    b.Property<DateTime?>("RespondedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("responded_at");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subject");

                    b.HasKey("Id")
                        .HasName("pk_help_requests");

                    b.HasIndex("MatriculantId")
                        .HasDatabaseName("ix_help_requests_matriculant_id");

                    b.HasIndex("MentorId")
                        .HasDatabaseName("ix_help_requests_mentor_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_help_requests_status");

                    b.ToTable("help_requests", (string)null);
                });

            modelBuilder.Entity("CareerAdvisor.Api.Models.Matriculant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<int?>("Grade")
                        .HasColumnType("integer")
                        .HasColumnName("grade");

                    b.Property<int>("MatricYear")
                        .HasColumnType("integer")
                        .HasColumnName("matric_year");

                    b.Property<string>("ProfileData")
                        .HasColumnType("jsonb")
                        .HasColumnName("profile_data");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("province");

                    b.Property<string>("School")
                        .HasColumnType("text")
                        .HasColumnName("school");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_matriculants");

                    b.HasIndex("Province")
                        .HasDatabaseName("ix_matriculants_province");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("matriculants_user_id_key");

                    b.ToTable("matriculants", (string)null);
                });

            modelBuilder.Entity("CareerAdvisor.Api.Models.MatriculantSubject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsHomeLanguage")
                        .HasColumnType("boolean")
                        .HasColumnName("is_home_language");

                    b.Property<Guid>("MatriculantId")
                        .HasColumnType("uuid")
                        .HasColumnName("matriculant_id");

                    b.Property<int>("Percentage")
                        .HasColumnType("integer")
                        .HasColumnName("percentage");

                    b.Property<string>("SubjectName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subject_name");

                    b.HasKey("Id")
                        .HasName("pk_matriculant_subjects");

                    b.HasIndex("MatriculantId")
                        .HasDatabaseName("ix_matriculant_subjects_matriculant");

                    b.HasIndex("MatriculantId", "SubjectName")
                        .IsUnique()
                        .HasDatabaseName("matriculant_subjects_unique");

                    b.ToTable("matriculant_subjects", (string)null);
                });

            modelBuilder.Entity("CareerAdvisor.Api.Models.Mentor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Area")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("area");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("bio");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Field")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("field");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<string>("InstitutionOrEmployer")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("institution_or_employer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("province");

                    b.Property<double?>("Rating")
                        .HasColumnType("double precision")
                        .HasColumnName("rating");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<int>("SessionsCompleted")
                        .HasColumnType("integer")
                        .HasColumnName("sessions_completed");

                    b.Property<Guid>("SourceApplicationId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_application_id");

                    b.Property<string[]>("Subjects")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("subjects");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string[]>("VerificationTiers")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("verification_tiers");

                    b.Property<string>("WorkEmail")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("work_email");

                    b.HasKey("Id")
                        .HasName("pk_mentors");

                    b.HasIndex("SourceApplicationId")
                        .IsUnique()
                        .HasDatabaseName("mentors_source_application_id_key");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("mentors_user_id_key");

                    b.ToTable("mentors", (string)null);
                });

            modelBuilder.Entity("CareerAdvisor.Api.Models.MentorApplication", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Claim")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("claim");

                    b.Property<bool>("ClaimsTeacher")
                        .HasColumnType("boolean")
                        .HasColumnName("claims_teacher");

                    b.Property<DateTime?>("DecidedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("decided_at");

                    b.Property<Guid?>("DecidedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("decided_by_user_id");

                    b.Property<string>("DuplicateOf")
                        .HasColumnType("text")
                        .HasColumnName("duplicate_of");

                    b.Property<string>("Field")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("field");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<string>("IdDocumentFilename")
                        .HasColumnType("text")
                        .HasColumnName("id_document_filename");

                    b.Property<string>("IdNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("id_number");

                    b.Property<string>("Institution")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("institution");

                    b.Property<string>("LicenceBody")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("licence_body");

                    b.Property<string>("LicenceNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("licence_number");

                    b.Property<string>("LinkedIn")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("linked_in");

                    b.Property<string>("PartnerCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("partner_code");

                    b.Property<string>("PartnerName")
                        .HasColumnType("text")
                        .HasColumnName("partner_name");

                    b.Property<string>("RiskFlags")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("risk_flags");

                    b.Property<int>("RiskScore")
                        .HasColumnType("integer")
                        .HasColumnName("risk_score");

                    b.Property<string>("RiskVerdict")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("risk_verdict");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("SubjectMismatch")
                        .HasColumnType("text")
                        .HasColumnName("subject_mismatch");

                    b.Property<string[]>("Subjects")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("subjects");

                    b.Property<int>("SubmitSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("submit_seconds");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<string>("TranscriptFilename")
                        .HasColumnType("text")
                        .HasColumnName("transcript_filename");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("WorkEmail")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("work_email");

                    b.HasKey("Id")
                        .HasName("pk_mentor_applications");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_mentor_applications_status");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_mentor_applications_user_id");

                    b.ToTable("mentor_applications", (string)null);
                });

            modelBuilder.Entity("CareerAdvisor.Api.Models.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<Guid>("HelpRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("help_request_id");

                    b.Property<string[]>("RedactedTypes")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("redacted_types");

                    b.Property<string>("SenderRole")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sender_role");

                    b.Property<Guid>("SenderUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("sender_user_id");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.HasKey("Id")
                        .HasName("pk_messages");

                    b.HasIndex("HelpRequestId", "SentAt")
                        .HasDatabaseName("ix_messages_request_sent");

                    b.ToTable("messages", (string)null);
                });

            modelBuilder.Entity("CareerAdvisor.Api.Models.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean")
                        .HasColumnName("is_read");

                    b.Property<string>("Target")
                        .HasColumnType("text")
                        .HasColumnName("target");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_notifications");

                    b.HasIndex("UserId", "IsRead")
                        .HasDatabaseName("ix_notifications_user_unread");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("CareerAdvisor.Api.Models.OfoCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_synced_at");

                    b.Property<string>("MajorGroup")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("major_group");

                    b.Property<string>("SubMinorGroup")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sub_minor_group");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_ofo_codes");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ofo_codes_code_key");

                    b.HasIndex("MajorGroup")
                        .HasDatabaseName("ix_ofo_codes_major_group");

                    b.ToTable("ofo_codes", (string)null);
                });

            modelBuilder.Entity("CareerAdvisor.Api.Models.RecommendationLetter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<Guid>("HelpRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("help_request_id");

                    b.Property<DateTime>("IssuedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issued_at");

                    b.Property<Guid>("IssuedByMentorId")
                        .HasColumnType("uuid")
                        .HasColumnName("issued_by_mentor_id");

                    b.Property<string>("ReferenceNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reference_number");

                    b.Property<string>("Strength")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("strength");

                    b.HasKey("Id")
                        .HasName("pk_recommendation_letters");

                    b.HasIndex("HelpRequestId")
                        .HasDatabaseName("ix_recommendation_letters_help_request_id");

                    b.HasIndex("IssuedByMentorId")
                        .HasDatabaseName("ix_recommendation_letters_issued_by_mentor_id");

                    b.ToTable("recommendation_letters", (string)null);
                });

            modelBuilder.Entity("CareerAdvisor.Api.Models.SaqaQualification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AwardingBody")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("awarding_body");

                    b.Property<int>("Credits")
                        .HasColumnType("integer")
                        .HasColumnName("credits");

                    b.Property<DateTime>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_synced_at");

                    b.Property<int>("NqfLevel")
                        .HasColumnType("integer")
                        .HasColumnName("nqf_level");

                    b.Property<string>("QualificationType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("qualification_type");

                    b.Property<string>("SaqaId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("saqa_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_saqa_qualifications");

                    b.HasIndex("NqfLevel")
                        .HasDatabaseName("ix_saqa_qualifications_nqf_level");

                    b.HasIndex("SaqaId")
                        .IsUnique()
                        .HasDatabaseName("saqa_qualifications_saqa_id_key");

                    b.ToTable("saqa_qualifications", (string)null);
                });

            modelBuilder.Entity("CareerAdvisor.Api.Models.University", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("province");

                    b.Property<string>("ShortCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("short_code");

                    b.Property<string>("Website")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("website");

                    b.HasKey("Id")
                        .HasName("pk_universities");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("universities_name_key");

                    b.HasIndex("Province")
                        .HasDatabaseName("ix_universities_province");

                    b.HasIndex("ShortCode")
                        .IsUnique()
                        .HasDatabaseName("universities_short_code_key");

                    b.ToTable("universities", (string)null);
                });

            modelBuilder.Entity("CareerAdvisor.Api.Models.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.HasKey("UserId")
                        .HasName("pk_user_roles");

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("CareerAdvisor.Api.Models.Course", b =>
                {
                    b.HasOne("CareerAdvisor.Api.Models.University", "University")
                        .WithMany("Courses")
                        .HasForeignKey("UniversityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_courses_universities_university_id");

                    b.Navigation("University");
                });

            modelBuilder.Entity("CareerAdvisor.Api.Models.CourseSubjectRequirement", b =>
                {
                    b.HasOne("CareerAdvisor.Api.Models.Course", "Course")
                        .WithMany("SubjectRequirements")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_course_subject_requirements_courses_course_id");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("CareerAdvisor.Api.Models.HelpRequest", b =>
                {
                    b.HasOne("CareerAdvisor.Api.Models.Matriculant", "Matriculant")
                        .WithMany()
                        .HasForeignKey("MatriculantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_help_requests_matriculants_matriculant_id");

                    b.HasOne("CareerAdvisor.Api.Models.Mentor", "Mentor")
                        .WithMany()
                        .HasForeignKey("MentorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_help_requests_mentors_mentor_id");

                    b.Navigation("Matriculant");

                    b.Navigation("Mentor");
                });

            modelBuilder.Entity("CareerAdvisor.Api.Models.MatriculantSubject", b =>
                {
                    b.HasOne("CareerAdvisor.Api.Models.Matriculant", "Matriculant")
                        .WithMany("Subjects")
                        .HasForeignKey("MatriculantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_matriculant_subjects_matriculants_matriculant_id");

                    b.Navigation("Matriculant");
                });

            modelBuilder.Entity("CareerAdvisor.Api.Models.Mentor", b =>
                {
                    b.HasOne("CareerAdvisor.Api.Models.MentorApplication", "SourceApplication")
                        .WithMany()
                        .HasForeignKey("SourceApplicationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_mentors_mentor_applications_source_application_id");

                    b.Navigation("SourceApplication");
                });

            modelBuilder.Entity("CareerAdvisor.Api.Models.Message", b =>
                {
                    b.HasOne("CareerAdvisor.Api.Models.HelpRequest", "HelpRequest")
                        .WithMany("Messages")
                        .HasForeignKey("HelpRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_messages_help_requests_help_request_id");

                    b.Navigation("HelpRequest");
                });

            modelBuilder.Entity("CareerAdvisor.Api.Models.RecommendationLetter", b =>
                {
                    b.HasOne("CareerAdvisor.Api.Models.HelpRequest", "HelpRequest")
                        .WithMany()
                        .HasForeignKey("HelpRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_recommendation_letters_help_requests_help_request_id");

                    b.HasOne("CareerAdvisor.Api.Models.Mentor", "IssuedByMentor")
                        .WithMany()
                        .HasForeignKey("IssuedByMentorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_recommendation_letters_mentors_issued_by_mentor_id");

                    b.Navigation("HelpRequest");

                    b.Navigation("IssuedByMentor");
                });

            modelBuilder.Entity("CareerAdvisor.Api.Models.Course", b =>
                {
                    b.Navigation("SubjectRequirements");
                });

            modelBuilder.Entity("CareerAdvisor.Api.Models.HelpRequest", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("CareerAdvisor.Api.Models.Matriculant", b =>
                {
                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("CareerAdvisor.Api.Models.University", b =>
                {
                    b.Navigation("Courses");
                });
#pragma warning restore 612, 618
        }
    }
}
